apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-ca
  namespace: homarr-v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDZzCCAk+gAwIBAgIUKb6cQqBXvb+jJCSJ1UBvpzt4KBIwDQYJKoZIhvcNAQEL
    BQAwIDEeMBwGA1UEAwwVYXV0aC5rcm9ja3lzcGhlcmUuY29tMB4XDTI2MDQyMTAx
    MjgxNVoXDTM2MDQxODAxMjgxNVowIDEeMBwGA1UEAwwVYXV0aC5rcm9ja3lzcGhl
    cmUuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7kQhdPShJu2I
    hcGC2xrkxFePKM2vyBAySATTxVYlsiIzeJV49Qr/RFgKmQJ1IjbFESLzqq8umMKe
    f7bJBxjlQvpTxWZQRCEOH3umLkf++qibXaXBi1b//FV82AAVEnTj6fAphHBcxs4c
    oR16xc/55MU+1t52OtxR17d7ge41FpxtsPsVXu01eJcQcmiMniQmu/NHfpHG0JJ4
    +aiP56DRWKVHYuDzVOWO0OkDFuIoycTaUQHlJiWUMnTFfREPztKLgoHYP7t6x1OY
    2kqWwe7RuC6UGGdMA2qCwrZtV0wz2TZW0s8aTZjQ/Ths7q6dSnICUoEDoYaY/xnS
    aUbbvj7RiQIDAQABo4GYMIGVMB0GA1UdDgQWBBQCmDVwn9kqxtldF1PrprwctH2t
    XTAfBgNVHSMEGDAWgBQCmDVwn9kqxtldF1PrprwctH2tXTAPBgNVHRMBAf8EBTAD
    AQH/MCAGA1UdEQQZMBeCFWF1dGgua3JvY2t5c3BoZXJlLmNvbTALBgNVHQ8EBAMC
    BaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDQYJKoZIhvcNAQELBQADggEBAH1nbi+Y
    7YTr/m+Ay2L4gZmlj67VY6nykUJzLz2MJeLyG5oWk0zDdM4UMICQvSV5Z1Oyr4WE
    Ds+k1vOeSlIVPvTtqx6pRo+gt1Xh+db1UWMf4KLA96BaxtBenT1tblduOOMAOF4v
    PnCklAtOjIU9avVDKL88tGfXi98yo70/luoLFbb0v7gDnJqkVcgSTAL6W0dUiwdM
    X4d5ZK+WfHf7p1gSVvOU+J5i6edgbQAN08oJQDIICRITPW6OMiPq5sKy4MSnarZS
    LyCkk/CWTzzF9v+aHD0ZanlIYH6mHagMLtJRWiao9Ro97b3n0PkaQcn9goqMEZrD
    Km84OynfVTrhTOY=
    -----END CERTIFICATE-----
