apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-v1-data-pvc
  namespace: homarr-v1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-v1-assets-pvc
  namespace: homarr-v1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
