---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    oidc.authentik.clientSecret: AgAZTy9fFv7zzxEewuml5RcA3PNn9/2gtu9XOd5LpUXv7kfcBwlRW5yGhioz4cEjeY28Niu/3OyOTHF1bUJmY4OozYGgHqzJtjQnJBNNYb47lBHIZrMB3AY2VLA0b64oNRaD/hntUuPwcJC9ffEgbvtviUfxmWtIvyx/UM8rVxnEx/CAsFW27dwfzUPm0W2Cixxscq2JDP56VNdUfM0zy81JnilR9/RjwS9zRbTZUqhkeU8pwPB3Jo7la+/c3ZIuQO/hguiM/tO591Xwy7KMgDyZJ6lGLZXIFc1kJh1+SETcrsCCC5LNNXU3kJep3D8MALebNzLsizRfRVzK771VInjJl39D5wBwHBMaP9LHQ9GbWDl/T7szB2PYNGMRwDelDZyVWMOUithsY5NTQeImF9KiggtExNom959avTJzzIFW7aJo4Lvv61CM4FsKkaD4EiZP8NE98tg01KiRBBhJWD+DE9kY0GGAHyyGkpfCb2CbgBLgkkvWT0XDUpYTNhiNvW9NsyLSbX/Il58YQHolQ332uEDICwnssV2oJZu66BwCrBnTvpXyP/qrKc/Zb0GFcdXHlxv/MTofNgWZVCsuOFvUuwXbbF2DH4yJLp0MZiFAGsXJoc+CFXyo3U1Hzfb41In9+As5BQoO/XQddAiGxz4guVTiACQk1OzOfon8onMn4KAyUhi93TyU5teTrDhSIY3i3NqNDHQbIO4tcTBUkncgjJTJ4E2IPhrwPqmAPDfRS19SKQiaaMCWoDYDjsaeg+iU/1/ZqZbqtrpXv+K1MKZzADXp1j7RjpqTVrnfy7E=
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
