apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/krocky5/homelab-k3s.git
    targetRevision: main
    path: services/arc
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
