apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/krocky5/homelab-k3s.git
    targetRevision: HEAD
    path: cloudflare-tunnel/cloudflared
  destination:
    server: https://kubernetes.default.svc
    namespace: tunnel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  # Ignore secret data (managed manually)
  ignoreDifferences:
  - group: ""
    kind: Secret
    jsonPointers:
    - /data
