---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: windmill-oauth-secret
  namespace: windmill
spec:
  encryptedData:
    oauth.json: AgCCAbNl6JeXCUidaNfusfjloCfmULJVue97Zz7SJwnzQNtv2rO5H46oRv1/wy2klJ9zHF1Ntww3spABacFSRwHqm3hFaU/uCu8JMeIO/QSlScn7+6g32EE8vYCOnyoqlI7O8oaY22YeMi/pJ4AwoqZjhR1HQ/y7ifvTsdb/UdECwMfIcnl051LohKMycyyzTfObqHx9dGEaiiY1zpEquFiDrtDrDqtaaEJQmf45BM9GpXH71Y1uLyWHe7ikuX2uOi+IAvqXFch4hdC3CBFe8KLtqFKu//PMCAovpXl6Mn8kMl0AvxBwy5O7yT3qhAEHkJ3hLgPqbWZON/sP6SO0QQ4dBNXos83GxclAGGvQ+TgCYmZx1GtWmVYQCKZyvV20AmBeTNTCI/Y+xmsQqh9J2YRLUa0AflLNwIccJIwmUCcuf2A++pFlpnB35RoJEOT9WaobjryZZ7wHYmRP2jfIppLUYyb9TEwf7K77DrTwxy93neEONKieLnGKL8Gbly5CFw4/48ze7Df89CjVSUCwYPInrbOekEiYeb0j7iz2mpY57xLpmvKxT5siWnOIhmtzAqHpPTEmgNg5qYIwd5pCGpC/IE0OjVQaOYCiOu/h4tmG/pEMs0cq0TQd+Y6jPAc8OgVmNrBigS3s6tmg5dWh1GdEzRjF0D0QC2Ko9paurEdZiegaFCKUhtr3uDbdAd3XCRO14I9oe8LD3x3YaSa4OkeWjuQrouzTtRTtQqdkvDjsAMh+ZO0AfRQ1N5ZIoG7j2tnHeY7j/cWBk8cy17QBH9trUIzt68NbqFvQpDizStrScjHVTKBXnoobI4d9cOMWZ1mh2IV0G9L6XhnVCvZ5UDpfG2RQdVinFf7Ixu+4txIeYhUu296h1uvzbnzSVQZLjAoo++J0r0T0tqPVjVt3Pr3hzgPYx3EruGcy/ez7ZoLp1QWmmyCqG/j/m5vp+KZK0yphCPzHmt4XPKtTCw2hmA/vrrcXZF3C4FlUyvZbz7B3iqWVOlsA6Xask9K7jaFdteWy/QGI9/IOwzq/Mx/QI2ggtrhCKLH1EBQmCuvcu9flYLRTAye1KXpAi9BM+Di3MnmGNaaJTK4KuwuBiQIk18Z8uzheYt9bsNDlBgQm2KGq32yR60+zNL7AyBNtvgTjxio5DdKO6PH71dCPcBo96DIcIji994Bsh0dGJEj6s7RBAs9B+a+WPy5FtRcQ4wjrcZOZIMCImXrDQUaCnIu/oGrzav9mJr54yHDvNOsqUMRBpRITuGHcl6+bDtJQ2U73dG7Mgt5sECizfNnn7gMHTbOEsQ==
  template:
    metadata:
      name: windmill-oauth-secret
      namespace: windmill
